### ISSUE TITLE
Rating info

### ISSUE THREAD

**Issue by kattisA** [kattisA/movie-app#8]
See if the OMDB API provides rating info and in that case add it to the card:
https://www.omdbapi.com/#usage

**Comment by ghost** [comment]
Yes, the OMDB API provides rating information about movies. You can use the built-in fetch function to make a request to the API endpoint and retrieve the rating data and then use the useState hook in React to store the retrieved data and render it on your page.

```JavaScript 
import React, { useState, useEffect } from 'react';

function MovieRating() {
  const [rating, setRating] = useState(null);

  useEffect(() => {
    fetch('http://www.omdbapi.com/?i=tt3896198&apikey=YOUR_API_KEY')
      .then(res => res.json())
      .then(data => {
        setRating(data.imdbRating);
      });
  }, []);

  return (
    <div>
      <h1>Movie Rating: {rating}</h1>
    </div>
  );
}

export default MovieRating;
```

The fetch function is used to make a request to the OMDB API using your API key. The retrieved data is then stored in the rating state variable using the setRating function. Finally, the rating data is rendered on the page using JSX.
